apiVersion: v1
kind: Namespace
metadata:
  name: __NAME_SPACE__
  labels:
    name: __NAME_SPACE__
---
apiVersion: v1
kind: Service
metadata:
  name: __DOMAIN_NAME__
  namespace: __NAME_SPACE__
spec:
  ports:
  - port: __CONTAINER_PORT__ # the port that this service should serve on
    # the container on each pod to connect to, can be a name
    # (e.g. 'www') or a number (e.g. 80)
    targetPort: __CONTAINER_PORT__
    protocol: TCP
  # just like the selector in the deployment,
  # but this time it identifies the set of pods to load balance
  # traffic to.
  selector:
    app: __DOMAIN_NAME__
---
apiVersion: apps/v1  # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: __DOMAIN_NAME__
  namespace: __NAME_SPACE__
spec:
  selector:
    matchLabels:
      app: __DOMAIN_NAME__
  replicas: __REPLICAS_NUM__ # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      # unlike pod-nginx.yaml, the name is not included in the meta data as a unique name is
      # generated from the deployment name
      labels:
        app: __DOMAIN_NAME__
    spec:
      containers:
      - name: __DOMAIN_NAME__
        image: __DOCKER_IMAGE__
        imagePullPolicy: IfNotPresent #本地存在就不到远程拉取镜像
        env: #环境变量设置
        - name: TZ
          value: Asia/Shanghai
        - name: PROFILE
          value: __PROFILE__
        - name: JAVA_OPTS
          value: "-server -Xms2048m -Xmx2048m"
        - name: CONTAINER_PORT
          value: "__CONTAINER_PORT__"
        - name: EUREKA_SERVER_ADDRESS
          value: __EUREKA_SERVER_ADDRESS__
        - name: DOMAIN_NAME
          value: __DOMAIN_NAME__
        envFrom:
        - configMapRef:
            name: __CONFIG_MAP__
        resources: #资源限制
          requests:
            memory: "128Mi"
            cpu: "100m" #最低需要 0.1个cpu
          limits:
            memory: "2048Mi"
            cpu: "800m"
        livenessProbe: #健康检查
          tcpSocket:
            port: __CONTAINER_PORT__
          initialDelaySeconds: 100
          timeoutSeconds: 1
        ports:
        - containerPort: __CONTAINER_PORT__
        volumeMounts:
        - name: time-config
          mountPath: /etc/localtime
          readOnly: true
      imagePullSecrets:
      - name: __DOCKER_REGISTRY_SECRET__
      volumes:
      - name: time-config
        hostPath:
          path: /etc/localtime
