classmanage:
  atndUrl: https://uther.talkedu.cn/service/sys/zhxyIndexAtndTe
weekly:
  threadPoolSize: 20
document:
  documentHost: http://zhx.tredu.gov.cn/
  compressPath: documentservice/documentConvert/compress.do
basedata:
  host: 
  getTermInfo: basedataApi/BaseDataService/getCurrentTermInfoId
point:
  gradeConfig: 9,29,89,209,389,629,969,1409,1949,2689,3629,4769
advice: 
   loginName: 31e62fb200e44722ac4112e749da9a77
my: 
   getPhoneValidate: http://openapi.tredu.gov.cn/basedataApi/user/sendVerifyCode
   updatePhoneByValidate: http://openapi.tredu.gov.cn/basedataApi/user/modifyMobileByVerifyCode
   updateUserPhoto: http://openapi.tredu.gov.cn/rrtApi/user/uploadUserPhoto
   judgeValidate: http://openapi.tredu.gov.cn/basedataApi/user/checkVerifyCode
   getUserByUserId: http://openapi.tredu.gov.cn/basedataApi/user/getUserByUserId/
   modifyUser: http://openapi.tredu.gov.cn/basedataApi/user/modifyUser
   getUsersByCondition: http://openapi.tredu.gov.cn/basedataApi/user/getUsersByCondition
   modifyPwdByVerifyCode: http://openapi.tredu.gov.cn/basedataApi/user/modifyPwdByVerifyCode
   updatePwd: http://openapi.tredu.gov.cn/basedataApi/user/modifyPwdCiphertext
   modifyEmailByVerifyCode: http://openapi.tredu.gov.cn/basedataApi/user/modifyEmailByVerifyCode
clientId: a977bccc-dfd4-11e7-9100-fa163ed3019d
secretId: 05216833-dfd5-11e7-9100-fa163ed3019d 
 
logging:
  config: classpath:logback-config.xml 
  
logback:
  logpath: /home/logs
  logfilecount: 10
  logfilesize: 200MB
  logpattern: '%d{yy-MM-dd HH:mm:ss.SSS} %5p [%15.15t] %40.40lo{40} : %m%n'
  logfile: ${logback.logpath}/${spring.application.name}/app.%d.txt
  logerrfile: ${logback.logpath}/${spring.application.name}/err.%d.txt
  addresslog: ${logback.logpath}/${spring.application.name}/address/address.%d.txt
  bannerlog: ${logback.logpath}/${spring.application.name}/banner/banner.%d.txt
  circlelog: ${logback.logpath}/${spring.application.name}/circle/circle.%d.txt
  classmanagelog: ${logback.logpath}/${spring.application.name}/classmanage/classmanage.%d.txt
  pointlog: ${logback.logpath}/${spring.application.name}/point/point.%d.txt
  weeklylog: ${logback.logpath}/${spring.application.name}/weekly/weekly.%d.txt
  advicelog: ${logback.logpath}/${spring.application.name}/advice/advice.%d.txt
 
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      #zt-product
       #defaultZone: http://zhx:zhx123@10.2.20.17:18001/eureka/
       #tr-product
       #defaultZone: http://zhx:zhx123@192.168.1.36:18001/eureka/
       #zhxy-product
       defaultZone: http://zhx:zhx123@192.168.1.36:18001/eureka/
 
spring:
 datasource:
    read:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.39:3306/?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&allowMultiQueries=true
      username: root
      password: Talkweb456#
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      validation-query: select 'x'
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
    write:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.39:3306/?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&allowMultiQueries=true
      username: root
      password: Talkweb456#
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      validation-query: select 'x'
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000

 sleuth:
    sampler:
      percentage: 0.1

#springboot 1.5.X 以上默认开通了安全认证，所以需要在配置文件application.properties添加以下配置，以post请求的方式来访问http://localhost:XX/refresh 就会更新修改后的配置文件  
management:
  security: 
    enabled: false
#hystrix
feign:
  hystrix:
  enabled: false
hystrix:
  shareSecurityContext: true
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 100000
        forceClosed: true
      execution:
        timeout:
          enabled:false
        isolation:
          thread:
            timeoutInMilliseconds: 60000000
ribbon:
  ReadTimeout: 6000000
  ConnectTimeout: 6000000
